import type { Product, EnvironmentalMetric, Certification, DiscountCode } from "@/types";

// Extended product specifications interface for filtering
export interface ExtendedProduct extends Product {
  processor?: string;
  processorType?: string;
  ram?: string;
  ramSize?: string;
  storage?: string;
  storageSize?: string;
  screenSize?: string;
  screenResolution?: string;
  graphics?: string;
  graphicsType?: string;
  os?: string;
  osType?: string;
  condition?: string;
  weight?: string;
  batteryLife?: string;
  releaseYear?: number;
  reviewCount?: number;
  rating?: number;
}

export const mockProducts: ExtendedProduct[] = [
  {
    id: "1",
    sku: "NOR-LAP-001",
    name: "Dell Latitude 5520 - Grade A",
    nameNo: "Dell Latitude 5520 - Grad A",
    description: "Excellent condition business laptop. Intel Core i5, 16GB RAM, 256GB SSD. Perfect for professional use.",
    descriptionNo: "Utmerket tilstand business bærbar. Intel Core i5, 16GB RAM, 256GB SSD. Perfekt for profesjonell bruk.",
    category: "LAPTOPS",
    brand: "Dell",
    model: "Latitude 5520",
    price: 5499,
    originalPrice: 12999,
    stock: 15,
    grade: "A",
    sustainabilityScore: 85,
    co2Saved: 285,
    images: ["/images/products/laptop-dell.jpg"],
    specifications: {
      "Processor": "Intel Core i5-1135G7",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Display": "15.6\" FHD",
      "OS": "Windows 11 Pro"
    },
    processor: "Intel Core i5-1135G7",
    processorType: "intel-i5",
    ram: "16GB DDR4",
    ramSize: "16",
    storage: "256GB NVMe SSD",
    storageSize: "256",
    screenSize: "15-16",
    screenResolution: "fhd",
    graphics: "Intel Iris Xe",
    graphicsType: "integrated",
    os: "Windows 11 Pro",
    osType: "windows-11",
    condition: "refurbished-a",
    weight: "1.8 kg",
    batteryLife: "10 hours",
    releaseYear: 2021,
    reviewCount: 24,
    rating: 4.5,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    id: "2",
    sku: "NOR-LAP-002",
    name: "HP EliteBook 840 G8 - Grade A",
    nameNo: "HP EliteBook 840 G8 - Grad A",
    description: "Premium ultrabook in excellent condition. Intel Core i7, 32GB RAM, 512GB SSD. Lightweight and powerful.",
    descriptionNo: "Premium ultrabook i utmerket tilstand. Intel Core i7, 32GB RAM, 512GB SSD. Lett og kraftig.",
    category: "LAPTOPS",
    brand: "HP",
    model: "EliteBook 840 G8",
    price: 7999,
    originalPrice: 18999,
    stock: 8,
    grade: "A",
    sustainabilityScore: 88,
    co2Saved: 295,
    images: ["/images/products/laptop-hp.jpg"],
    specifications: {
      "Processor": "Intel Core i7-1165G7",
      "RAM": "32GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Display": "14\" FHD",
      "OS": "Windows 11 Pro"
    },
    processor: "Intel Core i7-1165G7",
    processorType: "intel-i7",
    ram: "32GB DDR4",
    ramSize: "32",
    storage: "512GB NVMe SSD",
    storageSize: "512",
    screenSize: "13-14",
    screenResolution: "fhd",
    graphics: "Intel Iris Xe",
    graphicsType: "integrated",
    os: "Windows 11 Pro",
    osType: "windows-11",
    condition: "refurbished-a",
    weight: "1.34 kg",
    batteryLife: "12 hours",
    releaseYear: 2021,
    reviewCount: 18,
    rating: 4.7,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10")
  },
  {
    id: "3",
    sku: "NOR-LAP-003",
    name: "Lenovo ThinkPad T14 - Grade B",
    nameNo: "Lenovo ThinkPad T14 - Grad B",
    description: "Good condition ThinkPad with minor cosmetic wear. Intel Core i5, 16GB RAM, 256GB SSD.",
    descriptionNo: "God tilstand ThinkPad med mindre kosmetisk slitasje. Intel Core i5, 16GB RAM, 256GB SSD.",
    category: "LAPTOPS",
    brand: "Lenovo",
    model: "ThinkPad T14",
    price: 4299,
    originalPrice: 11999,
    stock: 12,
    grade: "B",
    sustainabilityScore: 75,
    co2Saved: 255,
    images: ["/images/products/laptop-lenovo.jpg"],
    specifications: {
      "Processor": "Intel Core i5-10310U",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Display": "14\" FHD",
      "OS": "Windows 11 Pro"
    },
    processor: "Intel Core i5-10310U",
    processorType: "intel-i5",
    ram: "16GB DDR4",
    ramSize: "16",
    storage: "256GB NVMe SSD",
    storageSize: "256",
    screenSize: "13-14",
    screenResolution: "fhd",
    graphics: "Intel UHD Graphics",
    graphicsType: "integrated",
    os: "Windows 11 Pro",
    osType: "windows-11",
    condition: "refurbished-b",
    weight: "1.55 kg",
    batteryLife: "8 hours",
    releaseYear: 2020,
    reviewCount: 32,
    rating: 4.3,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08")
  },
  {
    id: "4",
    sku: "NOR-MON-001",
    name: "Dell UltraSharp U2722D - Grade A",
    nameNo: "Dell UltraSharp U2722D - Grad A",
    description: "27\" 4K USB-C monitor in excellent condition. Perfect for professional work.",
    descriptionNo: "27\" 4K USB-C skjerm i utmerket tilstand. Perfekt for profesjonelt arbeid.",
    category: "MONITORS",
    brand: "Dell",
    model: "UltraSharp U2722D",
    price: 3999,
    originalPrice: 7499,
    stock: 6,
    grade: "A",
    sustainabilityScore: 82,
    co2Saved: 140,
    images: ["/images/products/monitor-dell.jpg"],
    specifications: {
      "Size": "27\"",
      "Resolution": "2560x1440 QHD",
      "Panel": "IPS",
      "Connectivity": "USB-C, HDMI, DP"
    },
    screenSize: "17-plus",
    screenResolution: "2k",
    condition: "refurbished-a",
    releaseYear: 2022,
    reviewCount: 15,
    rating: 4.6,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05")
  },
  {
    id: "5",
    sku: "NOR-PHN-001",
    name: "iPhone 13 Pro 256GB - Grade A",
    nameNo: "iPhone 13 Pro 256GB - Grad A",
    description: "Excellent condition iPhone 13 Pro with original battery health over 85%.",
    descriptionNo: "Utmerket tilstand iPhone 13 Pro med original batterihelse over 85%.",
    category: "PHONES",
    brand: "Apple",
    model: "iPhone 13 Pro",
    price: 6999,
    originalPrice: 13990,
    stock: 4,
    grade: "A",
    sustainabilityScore: 90,
    co2Saved: 48,
    images: ["/images/products/iphone-13pro.jpg"],
    specifications: {
      "Storage": "256GB",
      "Color": "Graphite",
      "Battery Health": "87%",
      "Condition": "Excellent"
    },
    processor: "Apple A15 Bionic",
    processorType: "apple-m1",
    storage: "256GB",
    storageSize: "256",
    screenSize: "under-13",
    screenResolution: "fhd",
    graphics: "Apple GPU",
    graphicsType: "apple-gpu",
    os: "iOS",
    osType: "macos",
    condition: "refurbished-a",
    releaseYear: 2021,
    reviewCount: 42,
    rating: 4.8,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12")
  },
  {
    id: "6",
    sku: "NOR-PHN-002",
    name: "Samsung Galaxy S22 Ultra - Grade B",
    nameNo: "Samsung Galaxy S22 Ultra - Grad B",
    description: "Good condition Galaxy S22 Ultra with minor screen wear. 256GB storage.",
    descriptionNo: "God tilstand Galaxy S22 Ultra med mindre skjermslitasje. 256GB lagring.",
    category: "PHONES",
    brand: "Samsung",
    model: "Galaxy S22 Ultra",
    price: 5499,
    originalPrice: 14990,
    stock: 3,
    grade: "B",
    sustainabilityScore: 78,
    co2Saved: 42,
    images: ["/images/products/samsung-s22.jpg"],
    specifications: {
      "Storage": "256GB",
      "Color": "Phantom Black",
      "Battery Health": "92%",
      "Condition": "Good"
    },
    storage: "256GB",
    storageSize: "256",
    screenSize: "under-13",
    screenResolution: "2k",
    condition: "refurbished-b",
    releaseYear: 2022,
    reviewCount: 28,
    rating: 4.4,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11")
  },
  {
    id: "7",
    sku: "NOR-DSK-001",
    name: "HP ProDesk 400 G7 - Grade A",
    nameNo: "HP ProDesk 400 G7 - Grad A",
    description: "Compact desktop PC in excellent condition. Intel Core i5, 16GB RAM, 256GB SSD.",
    descriptionNo: "Kompakt stasjonær PC i utmerket tilstand. Intel Core i5, 16GB RAM, 256GB SSD.",
    category: "DESKTOPS",
    brand: "HP",
    model: "ProDesk 400 G7",
    price: 3499,
    originalPrice: 8999,
    stock: 10,
    grade: "A",
    sustainabilityScore: 80,
    co2Saved: 380,
    images: ["/images/products/desktop-hp.jpg"],
    specifications: {
      "Processor": "Intel Core i5-10500",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Form Factor": "Small Form Factor"
    },
    processor: "Intel Core i5-10500",
    processorType: "intel-i5",
    ram: "16GB DDR4",
    ramSize: "16",
    storage: "256GB NVMe SSD",
    storageSize: "256",
    graphics: "Intel UHD Graphics 630",
    graphicsType: "integrated",
    os: "Windows 11 Pro",
    osType: "windows-11",
    condition: "refurbished-a",
    releaseYear: 2020,
    reviewCount: 11,
    rating: 4.2,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06")
  },
  {
    id: "8",
    sku: "NOR-TAB-001",
    name: "iPad Pro 11\" (2021) - Grade A",
    nameNo: "iPad Pro 11\" (2021) - Grad A",
    description: "M1 iPad Pro in excellent condition. 256GB WiFi model.",
    descriptionNo: "M1 iPad Pro i utmerket tilstand. 256GB WiFi-modell.",
    category: "TABLETS",
    brand: "Apple",
    model: "iPad Pro 11\" (2021)",
    price: 5999,
    originalPrice: 10990,
    stock: 5,
    grade: "A",
    sustainabilityScore: 86,
    co2Saved: 75,
    images: ["/images/products/ipad-pro.jpg"],
    specifications: {
      "Chip": "Apple M1",
      "Storage": "256GB",
      "Display": "11\" Liquid Retina",
      "Connectivity": "WiFi"
    },
    processor: "Apple M1",
    processorType: "apple-m1",
    storage: "256GB",
    storageSize: "256",
    screenSize: "under-13",
    screenResolution: "2k",
    graphics: "Apple GPU",
    graphicsType: "apple-gpu",
    os: "iPadOS",
    osType: "macos",
    condition: "refurbished-a",
    releaseYear: 2021,
    reviewCount: 19,
    rating: 4.7,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09")
  },
  {
    id: "9",
    sku: "NOR-ACC-001",
    name: "Apple Magic Keyboard - Grade B",
    nameNo: "Apple Magic Keyboard - Grad B",
    description: "Wireless keyboard with Touch ID in good condition.",
    descriptionNo: "Trådløst tastatur med Touch ID i god tilstand.",
    category: "ACCESSORIES",
    brand: "Apple",
    model: "Magic Keyboard",
    price: 799,
    originalPrice: 1790,
    stock: 20,
    grade: "B",
    sustainabilityScore: 70,
    co2Saved: 8.5,
    images: ["/images/products/keyboard-apple.jpg"],
    specifications: {
      "Type": "Wireless",
      "Features": "Touch ID",
      "Color": "Silver"
    },
    condition: "refurbished-b",
    releaseYear: 2021,
    reviewCount: 45,
    rating: 4.1,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07")
  },
  {
    id: "10",
    sku: "NOR-LAP-004",
    name: "MacBook Air M1 - Grade C",
    nameNo: "MacBook Air M1 - Grad C",
    description: "Functional MacBook Air with visible wear. 8GB RAM, 256GB SSD. Great value.",
    descriptionNo: "Funksjonell MacBook Air med synlig slitasje. 8GB RAM, 256GB SSD. God verdi.",
    category: "LAPTOPS",
    brand: "Apple",
    model: "MacBook Air M1",
    price: 5999,
    originalPrice: 11990,
    stock: 7,
    grade: "C",
    sustainabilityScore: 65,
    co2Saved: 210,
    images: ["/images/products/macbook-air.jpg"],
    specifications: {
      "Chip": "Apple M1",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "Display": "13.3\" Retina"
    },
    processor: "Apple M1",
    processorType: "apple-m1",
    ram: "8GB",
    ramSize: "8",
    storage: "256GB SSD",
    storageSize: "256",
    screenSize: "13-14",
    screenResolution: "2k",
    graphics: "Apple GPU",
    graphicsType: "apple-gpu",
    os: "macOS",
    osType: "macos",
    condition: "used",
    weight: "1.29 kg",
    batteryLife: "15 hours",
    releaseYear: 2020,
    reviewCount: 67,
    rating: 4.6,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14")
  },
  {
    id: "11",
    sku: "NOR-NET-001",
    name: "Cisco Catalyst Switch - Grade A",
    nameNo: "Cisco Catalyst Switch - Grad A",
    description: "Enterprise-grade 24-port network switch in excellent condition.",
    descriptionNo: "Enterprise-grad 24-ports nettverkssvitsj i utmerket tilstand.",
    category: "NETWORKING",
    brand: "Cisco",
    model: "Catalyst 2960-X",
    price: 2999,
    originalPrice: 8999,
    stock: 4,
    grade: "A",
    sustainabilityScore: 78,
    co2Saved: 28,
    images: ["/images/products/switch-cisco.jpg"],
    specifications: {
      "Ports": "24x Gigabit",
      "Management": "Layer 2",
      "PoE": "Yes"
    },
    condition: "refurbished-a",
    releaseYear: 2020,
    reviewCount: 8,
    rating: 4.4,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13")
  },
  {
    id: "12",
    sku: "NOR-STR-001",
    name: "WD My Book 8TB - Grade B",
    nameNo: "WD My Book 8TB - Grad B",
    description: "External hard drive in good working condition. 8TB capacity.",
    descriptionNo: "Ekstern harddisk i god stand. 8TB kapasitet.",
    category: "STORAGE",
    brand: "Western Digital",
    model: "My Book 8TB",
    price: 999,
    originalPrice: 2499,
    stock: 15,
    grade: "B",
    sustainabilityScore: 72,
    co2Saved: 17,
    images: ["/images/products/hdd-wd.jpg"],
    specifications: {
      "Capacity": "8TB",
      "Interface": "USB 3.0",
      "Type": "Desktop"
    },
    storage: "8TB",
    storageSize: "4096",
    condition: "refurbished-b",
    releaseYear: 2021,
    reviewCount: 22,
    rating: 4.0,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04")
  },
  // Additional products for variety
  {
    id: "13",
    sku: "NOR-LAP-005",
    name: "ASUS ROG Zephyrus G14 - Grade A",
    nameNo: "ASUS ROG Zephyrus G14 - Grad A",
    description: "Gaming laptop with AMD Ryzen 9 and RTX 3060. Excellent condition.",
    descriptionNo: "Gaming bærbar med AMD Ryzen 9 og RTX 3060. Utmerket tilstand.",
    category: "LAPTOPS",
    brand: "Asus",
    model: "ROG Zephyrus G14",
    price: 12999,
    originalPrice: 19999,
    stock: 3,
    grade: "A",
    sustainabilityScore: 75,
    co2Saved: 275,
    images: ["/images/products/laptop-asus-rog.jpg"],
    specifications: {
      "Processor": "AMD Ryzen 9 5900HS",
      "RAM": "32GB DDR4",
      "Storage": "1TB NVMe SSD",
      "Display": "14\" QHD 120Hz",
      "Graphics": "NVIDIA RTX 3060"
    },
    processor: "AMD Ryzen 9 5900HS",
    processorType: "amd-ryzen-9",
    ram: "32GB DDR4",
    ramSize: "32",
    storage: "1TB NVMe SSD",
    storageSize: "1024",
    screenSize: "13-14",
    screenResolution: "2k",
    graphics: "NVIDIA RTX 3060",
    graphicsType: "nvidia-rtx",
    os: "Windows 11 Home",
    osType: "windows-11",
    condition: "refurbished-a",
    weight: "1.7 kg",
    batteryLife: "10 hours",
    releaseYear: 2022,
    reviewCount: 35,
    rating: 4.8,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16")
  },
  {
    id: "14",
    sku: "NOR-LAP-006",
    name: "MacBook Pro 16\" M2 Pro - Grade A",
    nameNo: "MacBook Pro 16\" M2 Pro - Grad A",
    description: "Apple's professional laptop with M2 Pro chip. 32GB RAM, 512GB SSD.",
    descriptionNo: "Apples profesjonelle bærbar med M2 Pro brikke. 32GB RAM, 512GB SSD.",
    category: "LAPTOPS",
    brand: "Apple",
    model: "MacBook Pro 16\" M2 Pro",
    price: 22999,
    originalPrice: 34999,
    stock: 2,
    grade: "A",
    sustainabilityScore: 92,
    co2Saved: 320,
    images: ["/images/products/macbook-pro-16.jpg"],
    specifications: {
      "Chip": "Apple M2 Pro",
      "RAM": "32GB",
      "Storage": "512GB SSD",
      "Display": "16.2\" Liquid Retina XDR"
    },
    processor: "Apple M2 Pro",
    processorType: "apple-m2",
    ram: "32GB",
    ramSize: "32",
    storage: "512GB SSD",
    storageSize: "512",
    screenSize: "15-16",
    screenResolution: "4k",
    graphics: "Apple GPU 19-core",
    graphicsType: "apple-gpu",
    os: "macOS",
    osType: "macos",
    condition: "refurbished-a",
    weight: "2.14 kg",
    batteryLife: "22 hours",
    releaseYear: 2023,
    reviewCount: 12,
    rating: 4.9,
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17")
  },
  {
    id: "15",
    sku: "NOR-MON-002",
    name: "Samsung Odyssey G7 32\" - Grade A",
    nameNo: "Samsung Odyssey G7 32\" - Grad A",
    description: "Curved gaming monitor with 240Hz refresh rate and QHD resolution.",
    descriptionNo: "Buet gaming skjerm med 240Hz oppdateringsfrekvens og QHD oppløsning.",
    category: "MONITORS",
    brand: "Samsung",
    model: "Odyssey G7 32\"",
    price: 4999,
    originalPrice: 8999,
    stock: 4,
    grade: "A",
    sustainabilityScore: 78,
    co2Saved: 155,
    images: ["/images/products/monitor-samsung-g7.jpg"],
    specifications: {
      "Size": "32\"",
      "Resolution": "2560x1440 QHD",
      "Refresh Rate": "240Hz",
      "Panel": "VA Curved"
    },
    screenSize: "17-plus",
    screenResolution: "2k",
    condition: "refurbished-a",
    releaseYear: 2022,
    reviewCount: 28,
    rating: 4.5,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18")
  },
  {
    id: "16",
    sku: "NOR-DSK-002",
    name: "Dell OptiPlex 7090 - Grade A",
    nameNo: "Dell OptiPlex 7090 - Grad A",
    description: "Business desktop with Intel Core i7, 32GB RAM. Perfect for office work.",
    descriptionNo: "Business stasjonær med Intel Core i7, 32GB RAM. Perfekt for kontorarbeid.",
    category: "DESKTOPS",
    brand: "Dell",
    model: "OptiPlex 7090",
    price: 5999,
    originalPrice: 12999,
    stock: 6,
    grade: "A",
    sustainabilityScore: 82,
    co2Saved: 420,
    images: ["/images/products/desktop-dell.jpg"],
    specifications: {
      "Processor": "Intel Core i7-11700",
      "RAM": "32GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Form Factor": "Small Form Factor"
    },
    processor: "Intel Core i7-11700",
    processorType: "intel-i7",
    ram: "32GB DDR4",
    ramSize: "32",
    storage: "512GB NVMe SSD",
    storageSize: "512",
    graphics: "Intel UHD Graphics 750",
    graphicsType: "integrated",
    os: "Windows 11 Pro",
    osType: "windows-11",
    condition: "refurbished-a",
    releaseYear: 2021,
    reviewCount: 14,
    rating: 4.3,
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19")
  }
];

export const mockEnvironmentalMetrics: EnvironmentalMetric[] = [
  {
    id: "1",
    year: 2024,
    month: 1,
    devicesRecycled: 1247,
    co2SavedKg: 125000,
    eWasteKg: 8500,
    treesEquivalent: 5680
  },
  {
    id: "2",
    year: 2023,
    month: 12,
    devicesRecycled: 1156,
    co2SavedKg: 118000,
    eWasteKg: 7900,
    treesEquivalent: 5360
  }
];

export const mockCertifications: Certification[] = [
  {
    id: "1",
    name: "ISO 14001",
    nameNo: "ISO 14001",
    description: "Environmental Management System certification",
    descriptionNo: "Sertifisering for miljøstyringssystem",
    issuer: "ISO",
    validFrom: new Date("2022-01-01"),
    validUntil: new Date("2025-01-01"),
    imageUrl: "/images/certs/iso-14001.png",
    isActive: true
  },
  {
    id: "2",
    name: "R2 Certified",
    nameNo: "R2-sertifisert",
    description: "Responsible Recycling certification for electronics",
    descriptionNo: "Ansvarlig resirkulering-sertifisering for elektronikk",
    issuer: "SERI",
    validFrom: new Date("2023-06-01"),
    validUntil: new Date("2026-06-01"),
    imageUrl: "/images/certs/r2.png",
    isActive: true
  },
  {
    id: "3",
    name: "EU WEEE Compliance",
    nameNo: "EU WEEE-samsvar",
    description: "Compliant with EU Waste Electrical and Electronic Equipment directive",
    descriptionNo: "I samsvar med EUs direktiv om elektrisk og elektronisk avfall",
    issuer: "European Union",
    validFrom: new Date("2021-01-01"),
    validUntil: undefined,
    imageUrl: "/images/certs/weee.png",
    isActive: true
  },
  {
    id: "4",
    name: "Miljøfyrtårn",
    nameNo: "Miljøfyrtårn",
    description: "Norwegian Eco-Lighthouse certification",
    descriptionNo: "Norsk miljøsertifisering",
    issuer: "Stiftelsen Miljøfyrtårn",
    validFrom: new Date("2022-03-01"),
    validUntil: new Date("2025-03-01"),
    imageUrl: "/images/certs/miljofyrtarn.png",
    isActive: true
  }
];

// Aggregated environmental impact data
export const totalEnvironmentalImpact = {
  devicesRecycled: 15847,
  co2SavedTonnes: 1250,
  eWasteDivertedKg: 98500,
  treesEquivalent: 56800
};

// Brand list for filters
export const productBrands = [
  "Apple",
  "Dell",
  "HP",
  "Lenovo",
  "Samsung",
  "Asus",
  "Acer",
  "Microsoft",
  "Cisco",
  "Western Digital"
];

// Mock discount codes
export const mockDiscountCodes: DiscountCode[] = [
  {
    id: "1",
    code: "VELKOMMEN10",
    type: "percentage",
    value: 10,
    minOrderAmount: 500,
    maxUses: 1000,
    currentUses: 245,
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-12-31"),
    isActive: true,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "2",
    code: "NORNEX500",
    type: "fixed",
    value: 500,
    minOrderAmount: 3000,
    maxUses: 500,
    currentUses: 89,
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-12-31"),
    isActive: true,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "3",
    code: "MILJOVENN15",
    type: "percentage",
    value: 15,
    minOrderAmount: 2000,
    maxUses: 200,
    currentUses: 42,
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-06-30"),
    isActive: true,
    createdAt: new Date("2024-01-01")
  }
];

// Filter options for the advanced filter system
export const filterOptions = {
  categories: [
    { value: "LAPTOPS", labelNo: "Laptop", labelEn: "Laptop" },
    { value: "DESKTOPS", labelNo: "Desktop", labelEn: "Desktop" },
    { value: "TABLETS", labelNo: "Nettbrett", labelEn: "Tablet" },
    { value: "PHONES", labelNo: "Telefon", labelEn: "Phone" },
    { value: "MONITORS", labelNo: "Skjerm", labelEn: "Monitor" },
    { value: "ACCESSORIES", labelNo: "Tilbehør", labelEn: "Accessories" },
    { value: "NETWORKING", labelNo: "Nettverksutstyr", labelEn: "Networking" },
    { value: "STORAGE", labelNo: "Lagring", labelEn: "Storage" },
  ],
  processors: [
    { value: "intel-i3", labelNo: "Intel Core i3", labelEn: "Intel Core i3" },
    { value: "intel-i5", labelNo: "Intel Core i5", labelEn: "Intel Core i5" },
    { value: "intel-i7", labelNo: "Intel Core i7", labelEn: "Intel Core i7" },
    { value: "intel-i9", labelNo: "Intel Core i9", labelEn: "Intel Core i9" },
    { value: "amd-ryzen-3", labelNo: "AMD Ryzen 3", labelEn: "AMD Ryzen 3" },
    { value: "amd-ryzen-5", labelNo: "AMD Ryzen 5", labelEn: "AMD Ryzen 5" },
    { value: "amd-ryzen-7", labelNo: "AMD Ryzen 7", labelEn: "AMD Ryzen 7" },
    { value: "amd-ryzen-9", labelNo: "AMD Ryzen 9", labelEn: "AMD Ryzen 9" },
    { value: "apple-m1", labelNo: "Apple M1", labelEn: "Apple M1" },
    { value: "apple-m2", labelNo: "Apple M2", labelEn: "Apple M2" },
    { value: "apple-m3", labelNo: "Apple M3", labelEn: "Apple M3" },
  ],
  ramSizes: [
    { value: "4", labelNo: "4 GB", labelEn: "4 GB" },
    { value: "8", labelNo: "8 GB", labelEn: "8 GB" },
    { value: "16", labelNo: "16 GB", labelEn: "16 GB" },
    { value: "32", labelNo: "32 GB", labelEn: "32 GB" },
    { value: "64", labelNo: "64 GB", labelEn: "64 GB" },
    { value: "128", labelNo: "128 GB+", labelEn: "128 GB+" },
  ],
  storageSizes: [
    { value: "128", labelNo: "128 GB", labelEn: "128 GB" },
    { value: "256", labelNo: "256 GB", labelEn: "256 GB" },
    { value: "512", labelNo: "512 GB", labelEn: "512 GB" },
    { value: "1024", labelNo: "1 TB", labelEn: "1 TB" },
    { value: "2048", labelNo: "2 TB", labelEn: "2 TB" },
    { value: "4096", labelNo: "4 TB+", labelEn: "4 TB+" },
  ],
  screenSizes: [
    { value: "under-13", labelNo: "Under 13\"", labelEn: "Under 13\"" },
    { value: "13-14", labelNo: "13\" - 14\"", labelEn: "13\" - 14\"" },
    { value: "15-16", labelNo: "15\" - 16\"", labelEn: "15\" - 16\"" },
    { value: "17-plus", labelNo: "17\"+", labelEn: "17\"+" },
  ],
  screenResolutions: [
    { value: "fhd", labelNo: "Full HD (1920x1080)", labelEn: "Full HD (1920x1080)" },
    { value: "2k", labelNo: "2K (2560x1440)", labelEn: "2K (2560x1440)" },
    { value: "4k", labelNo: "4K (3840x2160)", labelEn: "4K (3840x2160)" },
    { value: "5k", labelNo: "5K+", labelEn: "5K+" },
  ],
  graphics: [
    { value: "integrated", labelNo: "Integrert grafikk", labelEn: "Integrated Graphics" },
    { value: "nvidia-gtx", labelNo: "NVIDIA GeForce GTX", labelEn: "NVIDIA GeForce GTX" },
    { value: "nvidia-rtx", labelNo: "NVIDIA GeForce RTX", labelEn: "NVIDIA GeForce RTX" },
    { value: "amd-radeon", labelNo: "AMD Radeon", labelEn: "AMD Radeon" },
    { value: "apple-gpu", labelNo: "Apple GPU", labelEn: "Apple GPU" },
  ],
  operatingSystems: [
    { value: "windows-11", labelNo: "Windows 11", labelEn: "Windows 11" },
    { value: "windows-10", labelNo: "Windows 10", labelEn: "Windows 10" },
    { value: "macos", labelNo: "macOS", labelEn: "macOS" },
    { value: "linux", labelNo: "Linux", labelEn: "Linux" },
    { value: "chromeos", labelNo: "Chrome OS", labelEn: "Chrome OS" },
    { value: "no-os", labelNo: "Ingen OS", labelEn: "No OS" },
  ],
  conditions: [
    { value: "new", labelNo: "Ny", labelEn: "New" },
    { value: "refurbished-a", labelNo: "Refurbished (Grad A)", labelEn: "Refurbished (Grade A)" },
    { value: "refurbished-b", labelNo: "Refurbished (Grad B)", labelEn: "Refurbished (Grade B)" },
    { value: "used", labelNo: "Brukt (God tilstand)", labelEn: "Used (Good condition)" },
  ],
  sortOptions: [
    { value: "newest", labelNo: "Nyeste først", labelEn: "Newest first" },
    { value: "price-low", labelNo: "Pris: lav til høy", labelEn: "Price: low to high" },
    { value: "price-high", labelNo: "Pris: høy til lav", labelEn: "Price: high to low" },
    { value: "name-asc", labelNo: "Navn: A-Å", labelEn: "Name: A-Z" },
    { value: "name-desc", labelNo: "Navn: Å-A", labelEn: "Name: Z-A" },
    { value: "popular", labelNo: "Mest populære", labelEn: "Most popular" },
    { value: "rating", labelNo: "Beste vurdering", labelEn: "Best rated" },
  ],
};
