import type { Product, EnvironmentalMetric, Certification } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    sku: "NOR-LAP-001",
    name: "Dell Latitude 5520 - Grade A",
    nameNo: "Dell Latitude 5520 - Grad A",
    description: "Excellent condition business laptop. Intel Core i5, 16GB RAM, 256GB SSD. Perfect for professional use.",
    descriptionNo: "Utmerket tilstand business bærbar. Intel Core i5, 16GB RAM, 256GB SSD. Perfekt for profesjonell bruk.",
    category: "LAPTOPS",
    brand: "Dell",
    model: "Latitude 5520",
    price: 5499,
    originalPrice: 12999,
    stock: 15,
    grade: "A",
    sustainabilityScore: 85,
    co2Saved: 285,
    images: ["/images/products/laptop-dell.jpg"],
    specifications: {
      "Processor": "Intel Core i5-1135G7",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Display": "15.6\" FHD",
      "OS": "Windows 11 Pro"
    },
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    id: "2",
    sku: "NOR-LAP-002",
    name: "HP EliteBook 840 G8 - Grade A",
    nameNo: "HP EliteBook 840 G8 - Grad A",
    description: "Premium ultrabook in excellent condition. Intel Core i7, 32GB RAM, 512GB SSD. Lightweight and powerful.",
    descriptionNo: "Premium ultrabook i utmerket tilstand. Intel Core i7, 32GB RAM, 512GB SSD. Lett og kraftig.",
    category: "LAPTOPS",
    brand: "HP",
    model: "EliteBook 840 G8",
    price: 7999,
    originalPrice: 18999,
    stock: 8,
    grade: "A",
    sustainabilityScore: 88,
    co2Saved: 295,
    images: ["/images/products/laptop-hp.jpg"],
    specifications: {
      "Processor": "Intel Core i7-1165G7",
      "RAM": "32GB DDR4",
      "Storage": "512GB NVMe SSD",
      "Display": "14\" FHD",
      "OS": "Windows 11 Pro"
    },
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10")
  },
  {
    id: "3",
    sku: "NOR-LAP-003",
    name: "Lenovo ThinkPad T14 - Grade B",
    nameNo: "Lenovo ThinkPad T14 - Grad B",
    description: "Good condition ThinkPad with minor cosmetic wear. Intel Core i5, 16GB RAM, 256GB SSD.",
    descriptionNo: "God tilstand ThinkPad med mindre kosmetisk slitasje. Intel Core i5, 16GB RAM, 256GB SSD.",
    category: "LAPTOPS",
    brand: "Lenovo",
    model: "ThinkPad T14",
    price: 4299,
    originalPrice: 11999,
    stock: 12,
    grade: "B",
    sustainabilityScore: 75,
    co2Saved: 255,
    images: ["/images/products/laptop-lenovo.jpg"],
    specifications: {
      "Processor": "Intel Core i5-10310U",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Display": "14\" FHD",
      "OS": "Windows 11 Pro"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08")
  },
  {
    id: "4",
    sku: "NOR-MON-001",
    name: "Dell UltraSharp U2722D - Grade A",
    nameNo: "Dell UltraSharp U2722D - Grad A",
    description: "27\" 4K USB-C monitor in excellent condition. Perfect for professional work.",
    descriptionNo: "27\" 4K USB-C skjerm i utmerket tilstand. Perfekt for profesjonelt arbeid.",
    category: "MONITORS",
    brand: "Dell",
    model: "UltraSharp U2722D",
    price: 3999,
    originalPrice: 7499,
    stock: 6,
    grade: "A",
    sustainabilityScore: 82,
    co2Saved: 140,
    images: ["/images/products/monitor-dell.jpg"],
    specifications: {
      "Size": "27\"",
      "Resolution": "2560x1440 QHD",
      "Panel": "IPS",
      "Connectivity": "USB-C, HDMI, DP"
    },
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05")
  },
  {
    id: "5",
    sku: "NOR-PHN-001",
    name: "iPhone 13 Pro 256GB - Grade A",
    nameNo: "iPhone 13 Pro 256GB - Grad A",
    description: "Excellent condition iPhone 13 Pro with original battery health over 85%.",
    descriptionNo: "Utmerket tilstand iPhone 13 Pro med original batterihelse over 85%.",
    category: "PHONES",
    brand: "Apple",
    model: "iPhone 13 Pro",
    price: 6999,
    originalPrice: 13990,
    stock: 4,
    grade: "A",
    sustainabilityScore: 90,
    co2Saved: 48,
    images: ["/images/products/iphone-13pro.jpg"],
    specifications: {
      "Storage": "256GB",
      "Color": "Graphite",
      "Battery Health": "87%",
      "Condition": "Excellent"
    },
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12")
  },
  {
    id: "6",
    sku: "NOR-PHN-002",
    name: "Samsung Galaxy S22 Ultra - Grade B",
    nameNo: "Samsung Galaxy S22 Ultra - Grad B",
    description: "Good condition Galaxy S22 Ultra with minor screen wear. 256GB storage.",
    descriptionNo: "God tilstand Galaxy S22 Ultra med mindre skjermslitasje. 256GB lagring.",
    category: "PHONES",
    brand: "Samsung",
    model: "Galaxy S22 Ultra",
    price: 5499,
    originalPrice: 14990,
    stock: 3,
    grade: "B",
    sustainabilityScore: 78,
    co2Saved: 42,
    images: ["/images/products/samsung-s22.jpg"],
    specifications: {
      "Storage": "256GB",
      "Color": "Phantom Black",
      "Battery Health": "92%",
      "Condition": "Good"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11")
  },
  {
    id: "7",
    sku: "NOR-DSK-001",
    name: "HP ProDesk 400 G7 - Grade A",
    nameNo: "HP ProDesk 400 G7 - Grad A",
    description: "Compact desktop PC in excellent condition. Intel Core i5, 16GB RAM, 256GB SSD.",
    descriptionNo: "Kompakt stasjonær PC i utmerket tilstand. Intel Core i5, 16GB RAM, 256GB SSD.",
    category: "DESKTOPS",
    brand: "HP",
    model: "ProDesk 400 G7",
    price: 3499,
    originalPrice: 8999,
    stock: 10,
    grade: "A",
    sustainabilityScore: 80,
    co2Saved: 380,
    images: ["/images/products/desktop-hp.jpg"],
    specifications: {
      "Processor": "Intel Core i5-10500",
      "RAM": "16GB DDR4",
      "Storage": "256GB NVMe SSD",
      "Form Factor": "Small Form Factor"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06")
  },
  {
    id: "8",
    sku: "NOR-TAB-001",
    name: "iPad Pro 11\" (2021) - Grade A",
    nameNo: "iPad Pro 11\" (2021) - Grad A",
    description: "M1 iPad Pro in excellent condition. 256GB WiFi model.",
    descriptionNo: "M1 iPad Pro i utmerket tilstand. 256GB WiFi-modell.",
    category: "TABLETS",
    brand: "Apple",
    model: "iPad Pro 11\" (2021)",
    price: 5999,
    originalPrice: 10990,
    stock: 5,
    grade: "A",
    sustainabilityScore: 86,
    co2Saved: 75,
    images: ["/images/products/ipad-pro.jpg"],
    specifications: {
      "Chip": "Apple M1",
      "Storage": "256GB",
      "Display": "11\" Liquid Retina",
      "Connectivity": "WiFi"
    },
    isActive: true,
    isFeatured: true,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09")
  },
  {
    id: "9",
    sku: "NOR-ACC-001",
    name: "Apple Magic Keyboard - Grade B",
    nameNo: "Apple Magic Keyboard - Grad B",
    description: "Wireless keyboard with Touch ID in good condition.",
    descriptionNo: "Trådløst tastatur med Touch ID i god tilstand.",
    category: "ACCESSORIES",
    brand: "Apple",
    model: "Magic Keyboard",
    price: 799,
    originalPrice: 1790,
    stock: 20,
    grade: "B",
    sustainabilityScore: 70,
    co2Saved: 8.5,
    images: ["/images/products/keyboard-apple.jpg"],
    specifications: {
      "Type": "Wireless",
      "Features": "Touch ID",
      "Color": "Silver"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07")
  },
  {
    id: "10",
    sku: "NOR-LAP-004",
    name: "MacBook Air M1 - Grade C",
    nameNo: "MacBook Air M1 - Grad C",
    description: "Functional MacBook Air with visible wear. 8GB RAM, 256GB SSD. Great value.",
    descriptionNo: "Funksjonell MacBook Air med synlig slitasje. 8GB RAM, 256GB SSD. God verdi.",
    category: "LAPTOPS",
    brand: "Apple",
    model: "MacBook Air M1",
    price: 5999,
    originalPrice: 11990,
    stock: 7,
    grade: "C",
    sustainabilityScore: 65,
    co2Saved: 210,
    images: ["/images/products/macbook-air.jpg"],
    specifications: {
      "Chip": "Apple M1",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "Display": "13.3\" Retina"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14")
  },
  {
    id: "11",
    sku: "NOR-NET-001",
    name: "Cisco Catalyst Switch - Grade A",
    nameNo: "Cisco Catalyst Switch - Grad A",
    description: "Enterprise-grade 24-port network switch in excellent condition.",
    descriptionNo: "Enterprise-grad 24-ports nettverkssvitsj i utmerket tilstand.",
    category: "NETWORKING",
    brand: "Cisco",
    model: "Catalyst 2960-X",
    price: 2999,
    originalPrice: 8999,
    stock: 4,
    grade: "A",
    sustainabilityScore: 78,
    co2Saved: 28,
    images: ["/images/products/switch-cisco.jpg"],
    specifications: {
      "Ports": "24x Gigabit",
      "Management": "Layer 2",
      "PoE": "Yes"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13")
  },
  {
    id: "12",
    sku: "NOR-STR-001",
    name: "WD My Book 8TB - Grade B",
    nameNo: "WD My Book 8TB - Grad B",
    description: "External hard drive in good working condition. 8TB capacity.",
    descriptionNo: "Ekstern harddisk i god stand. 8TB kapasitet.",
    category: "STORAGE",
    brand: "Western Digital",
    model: "My Book 8TB",
    price: 999,
    originalPrice: 2499,
    stock: 15,
    grade: "B",
    sustainabilityScore: 72,
    co2Saved: 17,
    images: ["/images/products/hdd-wd.jpg"],
    specifications: {
      "Capacity": "8TB",
      "Interface": "USB 3.0",
      "Type": "Desktop"
    },
    isActive: true,
    isFeatured: false,
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04")
  }
];

export const mockEnvironmentalMetrics: EnvironmentalMetric[] = [
  {
    id: "1",
    year: 2024,
    month: 1,
    devicesRecycled: 1247,
    co2SavedKg: 125000,
    eWasteKg: 8500,
    treesEquivalent: 5680
  },
  {
    id: "2",
    year: 2023,
    month: 12,
    devicesRecycled: 1156,
    co2SavedKg: 118000,
    eWasteKg: 7900,
    treesEquivalent: 5360
  }
];

export const mockCertifications: Certification[] = [
  {
    id: "1",
    name: "ISO 14001",
    nameNo: "ISO 14001",
    description: "Environmental Management System certification",
    descriptionNo: "Sertifisering for miljøstyringssystem",
    issuer: "ISO",
    validFrom: new Date("2022-01-01"),
    validUntil: new Date("2025-01-01"),
    imageUrl: "/images/certs/iso-14001.png",
    isActive: true
  },
  {
    id: "2",
    name: "R2 Certified",
    nameNo: "R2-sertifisert",
    description: "Responsible Recycling certification for electronics",
    descriptionNo: "Ansvarlig resirkulering-sertifisering for elektronikk",
    issuer: "SERI",
    validFrom: new Date("2023-06-01"),
    validUntil: new Date("2026-06-01"),
    imageUrl: "/images/certs/r2.png",
    isActive: true
  },
  {
    id: "3",
    name: "EU WEEE Compliance",
    nameNo: "EU WEEE-samsvar",
    description: "Compliant with EU Waste Electrical and Electronic Equipment directive",
    descriptionNo: "I samsvar med EUs direktiv om elektrisk og elektronisk avfall",
    issuer: "European Union",
    validFrom: new Date("2021-01-01"),
    validUntil: undefined,
    imageUrl: "/images/certs/weee.png",
    isActive: true
  },
  {
    id: "4",
    name: "Miljøfyrtårn",
    nameNo: "Miljøfyrtårn",
    description: "Norwegian Eco-Lighthouse certification",
    descriptionNo: "Norsk miljøsertifisering",
    issuer: "Stiftelsen Miljøfyrtårn",
    validFrom: new Date("2022-03-01"),
    validUntil: new Date("2025-03-01"),
    imageUrl: "/images/certs/miljofyrtarn.png",
    isActive: true
  }
];

// Aggregated environmental impact data
export const totalEnvironmentalImpact = {
  devicesRecycled: 15847,
  co2SavedTonnes: 1250,
  eWasteDivertedKg: 98500,
  treesEquivalent: 56800
};

// Brand list for filters
export const productBrands = [
  "Apple",
  "Dell",
  "HP",
  "Lenovo",
  "Samsung",
  "Cisco",
  "Western Digital"
];
