import type {
  PortalOrder,
  PortalRepair,
  PortalTradeIn,
  PortalInvoice,
  PortalTicket,
  PortalContract,
  FleetDevice,
  TeamMember,
  PortalAnalytics,
} from '@/types/portal';

// Mock Orders
export const mockOrders: PortalOrder[] = [
  {
    id: 'ord-1',
    orderNumber: 'NOR-ABC123',
    status: 'SHIPPED',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    items: [
      { id: 'item-1', productName: 'Dell Latitude 5520 - Grad A', quantity: 1, price: 5499, image: '/images/products/laptop-dell.jpg' },
      { id: 'item-2', productName: 'Apple Magic Keyboard - Grad B', quantity: 2, price: 799, image: '/images/products/keyboard-apple.jpg' },
    ],
    subtotal: 7097,
    tax: 1774.25,
    shipping: 99,
    total: 8970.25,
    trackingNumber: 'PO123456789NO',
    estimatedDelivery: new Date(Date.now() + 1000 * 60 * 60 * 24),
    department: 'IT-avdeling',
  },
  {
    id: 'ord-2',
    orderNumber: 'NOR-DEF456',
    status: 'PROCESSING',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
    items: [
      { id: 'item-3', productName: 'HP EliteBook 840 G8 - Grad A', quantity: 1, price: 7999, image: '/images/products/laptop-hp.jpg' },
    ],
    subtotal: 7999,
    tax: 1999.75,
    shipping: 0,
    total: 9998.75,
    department: 'Salg',
  },
  {
    id: 'ord-3',
    orderNumber: 'NOR-GHI789',
    status: 'DELIVERED',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10),
    items: [
      { id: 'item-4', productName: 'iPhone 13 Pro 256GB - Grad A', quantity: 1, price: 6999, image: '/images/products/iphone-13pro.jpg' },
    ],
    subtotal: 6999,
    tax: 1749.75,
    shipping: 49,
    total: 8797.75,
  },
  {
    id: 'ord-4',
    orderNumber: 'NOR-JKL012',
    status: 'PENDING',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    items: [
      { id: 'item-5', productName: 'Dell UltraSharp U2722D - Grad A', quantity: 2, price: 3999, image: '/images/products/monitor-dell.jpg' },
    ],
    subtotal: 7998,
    tax: 1999.50,
    shipping: 149,
    total: 10146.50,
    department: 'Administrasjon',
  },
];

// Mock Repairs
export const mockRepairs: PortalRepair[] = [
  {
    id: 'rep-1',
    ticketNumber: 'REP-001',
    deviceType: 'Laptop',
    deviceBrand: 'Dell',
    deviceModel: 'Latitude 5520',
    status: 'COMPLETED',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    estimatedCost: 2500,
    finalCost: 2350,
    description: 'Skjermen flimrer og batteri varer ikke lenge',
    technicianNotes: 'Byttet LCD-panel og batteri. Alt fungerer nå perfekt.',
    parts: [
      { id: 'part-1', name: 'LCD Panel 15.6" FHD', price: 1500, quantity: 1 },
      { id: 'part-2', name: 'Battery 4-cell 68Wh', price: 650, quantity: 1 },
    ],
    laborHours: 2,
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    department: 'IT-avdeling',
  },
  {
    id: 'rep-2',
    ticketNumber: 'REP-002',
    deviceType: 'Telefon',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 13',
    status: 'IN_PROGRESS',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    estimatedCost: 1800,
    description: 'Sprukket skjerm etter fall',
    technicianNotes: 'Venter på originale Apple-deler.',
    parts: [
      { id: 'part-3', name: 'iPhone 13 Display Assembly', price: 1500, quantity: 1 },
    ],
    laborHours: 1,
  },
  {
    id: 'rep-3',
    ticketNumber: 'REP-003',
    deviceType: 'Desktop',
    deviceBrand: 'HP',
    deviceModel: 'ProDesk 400 G7',
    status: 'DIAGNOSING',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    description: 'PC starter ikke, bare blinkende lys',
    department: 'Salg',
  },
  {
    id: 'rep-4',
    ticketNumber: 'REP-004',
    deviceType: 'Laptop',
    deviceBrand: 'Lenovo',
    deviceModel: 'ThinkPad T14',
    status: 'READY_FOR_PICKUP',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    estimatedCost: 800,
    finalCost: 750,
    description: 'Tastatur fungerer ikke riktig',
    technicianNotes: 'Byttet tastatur. Testet og fungerer perfekt.',
    parts: [
      { id: 'part-4', name: 'ThinkPad T14 Keyboard NO', price: 550, quantity: 1 },
    ],
    laborHours: 0.5,
    completedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    department: 'Administrasjon',
  },
];

// Mock Trade-ins
export const mockTradeIns: PortalTradeIn[] = [
  {
    id: 'trade-1',
    requestNumber: 'TRD-001',
    deviceType: 'Laptop',
    brand: 'Apple',
    model: 'MacBook Pro 2019',
    condition: 'GOOD',
    status: 'INSPECTED',
    estimatedValue: 4500,
    finalValue: 4200,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: 'trade-2',
    requestNumber: 'TRD-002',
    deviceType: 'Telefon',
    brand: 'Samsung',
    model: 'Galaxy S21',
    condition: 'EXCELLENT',
    status: 'QUOTE_SENT',
    estimatedValue: 3000,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
  {
    id: 'trade-3',
    requestNumber: 'TRD-003',
    deviceType: 'Desktop',
    brand: 'Dell',
    model: 'OptiPlex 7080',
    condition: 'FAIR',
    status: 'COMPLETED',
    estimatedValue: 2000,
    finalValue: 1800,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
  },
];

// Mock Invoices
export const mockInvoices: PortalInvoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: '2024-0089',
    orderId: 'ord-1',
    amount: 7097,
    tax: 1774.25,
    total: 8970.25,
    status: 'PAID',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    paidAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
    downloadUrl: '/api/invoices/2024-0089/pdf',
  },
  {
    id: 'inv-2',
    invoiceNumber: '2024-0088',
    orderId: 'ord-3',
    amount: 6999,
    tax: 1749.75,
    total: 8797.75,
    status: 'PAID',
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15),
    paidAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14),
    downloadUrl: '/api/invoices/2024-0088/pdf',
  },
  {
    id: 'inv-3',
    invoiceNumber: '2024-0090',
    repairId: 'rep-1',
    amount: 2350,
    tax: 587.50,
    total: 2937.50,
    status: 'PENDING',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    downloadUrl: '/api/invoices/2024-0090/pdf',
  },
  {
    id: 'inv-4',
    invoiceNumber: '2024-0085',
    amount: 15000,
    tax: 3750,
    total: 18750,
    status: 'OVERDUE',
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35),
    downloadUrl: '/api/invoices/2024-0085/pdf',
  },
];

// Mock Support Tickets
export const mockTickets: PortalTicket[] = [
  {
    id: 'ticket-1',
    ticketNumber: 'SUP-001',
    subject: 'Spørsmål om garanti',
    description: 'Jeg lurer på om garantien dekker skader som har oppstått etter 6 måneder.',
    status: 'OPEN',
    priority: 'MEDIUM',
    category: 'Garanti',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    messages: [
      {
        id: 'msg-1',
        content: 'Jeg kjøpte en laptop for 6 måneder siden, og nå har skjermen begynt å flimre. Er dette dekket av garantien?',
        isStaff: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
      },
      {
        id: 'msg-2',
        content: 'Hei! Takk for at du kontaktet oss. Ja, alle våre produkter har 12 måneders garanti. Vi kan ordne en gratis reparasjon. Vennligst send inn enheten via vårt reparasjonsskjema.',
        isStaff: true,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
      },
    ],
  },
  {
    id: 'ticket-2',
    ticketNumber: 'SUP-002',
    subject: 'Mangler tilbehør i pakken',
    description: 'Lader manglet i pakken med laptopen.',
    status: 'RESOLVED',
    priority: 'HIGH',
    category: 'Levering',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
    messages: [
      {
        id: 'msg-3',
        content: 'Min laptop ankom uten lader. Kan dere sende en?',
        isStaff: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5),
      },
      {
        id: 'msg-4',
        content: 'Beklager dette! Vi sender en lader i dag med ekspress levering.',
        isStaff: true,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4),
      },
      {
        id: 'msg-5',
        content: 'Mottatt! Takk for rask hjelp.',
        isStaff: false,
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      },
    ],
  },
];

// Mock Contracts (Company only)
export const mockContracts: PortalContract[] = [
  {
    id: 'contract-1',
    contractNumber: 'CON-2024-001',
    title: 'IT Support Avtale',
    type: 'SUPPORT',
    status: 'ACTIVE',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-12-31'),
    value: 120000,
    autoRenew: true,
    daysUntilExpiry: 35,
    documents: [
      { id: 'doc-1', name: 'Kontrakt signert.pdf', type: 'pdf', url: '/api/documents/con-2024-001', uploadedAt: new Date('2024-01-01') },
    ],
  },
  {
    id: 'contract-2',
    contractNumber: 'CON-2024-002',
    title: 'Vedlikeholdsavtale - Fleet',
    type: 'MAINTENANCE',
    status: 'EXPIRING_SOON',
    startDate: new Date('2023-06-01'),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25),
    value: 85000,
    autoRenew: false,
    daysUntilExpiry: 25,
  },
  {
    id: 'contract-3',
    contractNumber: 'CON-2023-005',
    title: 'SLA Premium Support',
    type: 'SLA',
    status: 'ACTIVE',
    startDate: new Date('2023-01-01'),
    endDate: new Date('2025-12-31'),
    value: 250000,
    autoRenew: true,
    daysUntilExpiry: 400,
  },
  {
    id: 'contract-4',
    contractNumber: 'CON-2024-003',
    title: 'Leasing - 10 Laptops',
    type: 'LEASE',
    status: 'EXPIRING_SOON',
    startDate: new Date('2022-03-01'),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60),
    value: 180000,
    autoRenew: false,
    daysUntilExpiry: 60,
  },
];

// Mock Fleet Devices (Company only)
export const mockFleetDevices: FleetDevice[] = [
  { id: 'device-1', assetTag: 'NOR-LAP-001', deviceType: 'Laptop', brand: 'Dell', model: 'Latitude 5520', serialNumber: 'DL5520-001', assignedTo: 'Ola Hansen', department: 'IT-avdeling', status: 'ACTIVE', purchaseDate: new Date('2023-06-15'), warrantyExpiry: new Date('2024-06-15') },
  { id: 'device-2', assetTag: 'NOR-LAP-002', deviceType: 'Laptop', brand: 'HP', model: 'EliteBook 840', serialNumber: 'HP840-002', assignedTo: 'Kari Olsen', department: 'Salg', status: 'ACTIVE', purchaseDate: new Date('2023-08-20'), warrantyExpiry: new Date('2024-08-20') },
  { id: 'device-3', assetTag: 'NOR-LAP-003', deviceType: 'Laptop', brand: 'Lenovo', model: 'ThinkPad T14', serialNumber: 'LEN-T14-003', assignedTo: 'Per Nilsen', department: 'Administrasjon', status: 'IN_REPAIR', purchaseDate: new Date('2023-05-10'), warrantyExpiry: new Date('2024-05-10'), lastMaintenanceDate: new Date('2024-01-15') },
  { id: 'device-4', assetTag: 'NOR-MON-001', deviceType: 'Monitor', brand: 'Dell', model: 'UltraSharp U2722D', assignedTo: 'Ola Hansen', department: 'IT-avdeling', status: 'ACTIVE', purchaseDate: new Date('2023-06-15') },
  { id: 'device-5', assetTag: 'NOR-PHN-001', deviceType: 'Telefon', brand: 'Apple', model: 'iPhone 13 Pro', serialNumber: 'IP13-001', assignedTo: 'Direktør', department: 'Ledelse', status: 'ACTIVE', purchaseDate: new Date('2023-09-01'), warrantyExpiry: new Date('2024-09-01') },
  { id: 'device-6', assetTag: 'NOR-LAP-004', deviceType: 'Laptop', brand: 'Dell', model: 'Latitude 5530', status: 'AVAILABLE', purchaseDate: new Date('2024-01-10'), warrantyExpiry: new Date('2025-01-10') },
  { id: 'device-7', assetTag: 'NOR-DSK-001', deviceType: 'Desktop', brand: 'HP', model: 'ProDesk 400', serialNumber: 'HP400-001', department: 'Fellesområde', status: 'ACTIVE', purchaseDate: new Date('2023-03-20') },
];

// Mock Team Members (Company only)
export const mockTeamMembers: TeamMember[] = [
  { id: 'team-1', name: 'Kari Bedriftsen', email: 'kari@bedrift.no', role: 'OWNER', isActive: true, lastLogin: new Date(), permissions: ['all'] },
  { id: 'team-2', name: 'Ola Hansen', email: 'ola@bedrift.no', role: 'ADMIN', department: 'IT-avdeling', isActive: true, lastLogin: new Date(Date.now() - 1000 * 60 * 60), permissions: ['manage_orders', 'manage_repairs', 'manage_fleet'] },
  { id: 'team-3', name: 'Per Nilsen', email: 'per@bedrift.no', role: 'MANAGER', department: 'Administrasjon', isActive: true, lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24), permissions: ['view_orders', 'create_orders', 'view_reports'] },
  { id: 'team-4', name: 'Lise Olsen', email: 'lise@bedrift.no', role: 'MEMBER', department: 'Salg', isActive: true, lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 48), permissions: ['view_orders', 'create_orders'] },
  { id: 'team-5', name: 'Erik Johansen', email: 'erik@bedrift.no', role: 'VIEWER', department: 'Salg', isActive: false, permissions: ['view_orders'] },
];

// Mock Analytics (Company only)
export const mockAnalytics: PortalAnalytics = {
  totalOrders: 47,
  totalSpent: 385000,
  activeDevices: 28,
  pendingRepairs: 3,
  expiringContracts: 2,
  openTickets: 1,
  monthlySpending: [
    { month: 'Jan', amount: 45000 },
    { month: 'Feb', amount: 32000 },
    { month: 'Mar', amount: 58000 },
    { month: 'Apr', amount: 41000 },
    { month: 'Mai', amount: 67000 },
    { month: 'Jun', amount: 52000 },
    { month: 'Jul', amount: 28000 },
    { month: 'Aug', amount: 62000 },
  ],
  departmentSpending: [
    { department: 'IT-avdeling', amount: 145000, orderCount: 18 },
    { department: 'Salg', amount: 98000, orderCount: 15 },
    { department: 'Administrasjon', amount: 67000, orderCount: 8 },
    { department: 'Ledelse', amount: 45000, orderCount: 4 },
    { department: 'Andre', amount: 30000, orderCount: 2 },
  ],
};
